export const COLORS = {
  primary: "#B89354",
  accent: "#785920",
  secondary: "#4B5563",
  canvas: "#FFF8F5",
  body: "#201B16",
  surface: "#ECE0D9",
  inactive: "#A8A29E",
  active: "#B45309",
};

export const CURRENCY = "د.ت";

export const CATEGORIES = [
  { title: "مجوهرات", icon: "../../assets/images/icons/diamon.svg" },
  { title: "ساعات", icon: "../../assets/images/icons/watch.svg" },
  { title: "عطور", icon: "../../assets/images/icons/dress.svg" },
  { title: "ملابس", icon: "../../assets/images/icons/dress.svg" },
  { title: "باخور", icon: "../../assets/images/icons/dress.svg" },
  { title: "حقائب يد", icon: "../../assets/images/icons/dress.svg" },
  { title: "إكسسوارات", icon: "../../assets/images/icons/dress.svg" },
  { title: "أحذية", icon: "../../assets/images/icons/dress.svg" },
  { title: "مكياج", icon: "../../assets/images/icons/dress.svg" },
];

export const COLLECTIONS = [
  {
    _id: "1",
    banner: "https://69f78dbca0be0e562864a507.imgix.net/afnen.png",
    cta: "استكشف الآن",
    title: "أفنان",
    subtitle: "On everything today",
    isFeatured: true,
    isActive: true,
    products: [
      {
        _id: "11",
        name: "أنا الأبيض",
        type: "simple",
        subtitle: "نسخة محدودة • ١٠٠ مل",
        description: "",
        sizes: null,
        category: "عطور",
        price: 180,
        stock: 100,
        isFeatured: true,
        images: [
          "https://69f78dbca0be0e562864a507.imgix.net/parfum_ana_abiyedh_rouge.png",
        ],
        isActive: true,
        createdAt: "2026-05-02T21:45:27.922+00:0",
      },
      {
        _id: "12",
        name: "عود الليل الملكي",
        type: "simple",
        subtitle: "نسخة محدودة • ١٠٠ مل",
        price: 250,
        description: "",
        sizes: null,
        category: "عطور",
        stock: 10,
        isFeatured: true,
        images: [
          "https://69f78dbca0be0e562864a507.imgix.net/parfum_oud_lail_maleki.png",
        ],
        isActive: true,
        createdAt: "2026-05-03T21:45:27.922+00:0",
      },
      {
        _id: "13",
        name: "أسد",
        type: "simple",
        subtitle: "نسخة محدودة • ١٠٠ مل",
        price: 250,
        description: "",
        sizes: null,
        category: "عطور",
        stock: 10,
        isFeatured: true,
        images: ["https://69f78dbca0be0e562864a507.imgix.net/parfum_assad.png"],
        isActive: true,
        createdAt: "2026-05-02T21:45:27.922+00:0",
      },
      {
        _id: "14",
        name: "24 قراط ذهب",
        type: "simple",
        subtitle: "نسخة محدودة • ١٠٠ مل",
        price: 250,
        description: "",
        sizes: null,
        category: "عطور",
        stock: 10,
        isFeatured: true,
        images: [
          "https://69f78dbca0be0e562864a507.imgix.net/parfum_24_carat_pure_gold.png",
        ],
        isActive: true,
        createdAt: "2026-05-01T21:45:27.922+00:0",
      },
    ],
  },
  {
    _id: "2",
    banner: "https://69f78dbca0be0e562864a507.imgix.net/achwak.png",
    cta: "استكشف الآن",
    title: "أشواق",
    subtitle: "On everything today",
    isFeatured: true,
    isActive: true,

    products: [
      {
        _id: "21",
        name: "بن نافع للعود",
        type: "simple",
        subtitle: "بن نافع للعود",
        price: 180,
        description: "",
        sizes: null,
        category: "باخور",
        stock: 10,
        isFeatured: true,
        images: [
          "https://69f78dbca0be0e562864a507.imgix.net/bakour_banafa_for_oud.png",
        ],
        isActive: true,
        createdAt: "2026-05-04T24:45:27.922+00:0",
      },
      {
        _id: "22",
        name: "بخور كويتي",
        type: "simple",
        subtitle: "بخور كويتي",
        price: 180,

        description: "",
        sizes: null,
        category: "باخور",
        stock: 10,
        isFeatured: true,
        images: [
          "https://69f78dbca0be0e562864a507.imgix.net/bakour_kwaiti.png",
        ],
        isActive: true,
        createdAt: "2026-05-03T24:45:27.922+00:0",
      },
      {
        _id: "23",
        name: "عود فاخر",
        type: "simple",
        price: 250,

        description: "",
        sizes: null,
        category: "باخور",
        stock: 10,
        isFeatured: true,
        images: [
          "https://69f78dbca0be0e562864a507.imgix.net/bakour_oud_wood.png",
        ],
        isActive: true,
        createdAt: "2026-05-02T24:45:27.922+00:0",
      },
      {
        _id: "24",
        name: "بخور عشق العرب",
        type: "simple",
        subtitle: "بخور عشق العرب",
        price: 350,
        description: "",
        sizes: null,
        category: "باخور",
        stock: 10,
        isFeatured: true,
        images: [
          "https://69f78dbca0be0e562864a507.imgix.net/bakour_acheg_al_arab.png",
        ],
        isActive: true,
        createdAt: "2026-05-01T24:45:27.922+00:0",
      },
    ],
  },
  {
    _id: "3",
    banner: "https://69f78dbca0be0e562864a507.imgix.net/rawnak.png",
    cta: "استكشف الآن",
    title: "رونق",
    subtitle: "On everything today",
    isFeatured: true,
    isActive: true,

    products: [
      {
        _id: "31",
        name: "luxury watch",
        type: "simple",
        subtitle: "luxury watch",
        price: 80,

        description: "",
        sizes: null,
        category: "ساعات",
        stock: 100,
        isFeatured: true,
        images: ["https://69f78dbca0be0e562864a507.imgix.net/watch_luxury.png"],
        isActive: true,
        createdAt: "2026-05-04T24:45:27.922+00:0",
      },
      {
        _id: "32",
        name: "ressence type 11",
        type: "simple",
        subtitle: "ressence type 11",
        price: 80,

        description: "",
        sizes: null,
        category: "ساعات",
        stock: 10,
        isFeatured: true,
        images: [
          "https://69f78dbca0be0e562864a507.imgix.net/watch_ressence_type_11.png",
        ],
        isActive: true,
        createdAt: "2026-05-03T24:45:27.922+00:0",
      },
      {
        _id: "33",
        name: "inspiration one",
        type: "simple",
        subtitle: "inspiration one",
        price: 80,

        description: "",
        sizes: null,
        category: "ساعات",
        stock: 10,
        isFeatured: true,
        images: [
          "https://69f78dbca0be0e562864a507.imgix.net/watch_inspiration.png",
        ],
        isActive: true,
        createdAt: "2026-05-02T24:45:27.922+00:0",
      },
      {
        _id: "34",
        name: "nautilus 5610p",
        type: "simple",
        subtitle: "nautilus 5610p",
        price: 80,

        description: "",
        sizes: null,
        category: "ساعات",
        stock: 10,
        isFeatured: true,
        images: [
          "https://69f78dbca0be0e562864a507.imgix.net/watch_patek_philip.png",
        ],
        isActive: true,
        createdAt: "2026-05-01T24:45:27.922+00:0",
      },
    ],
  },

  {
    _id: "4",
    banner: "https://69f78dbca0be0e562864a507.imgix.net/zina_arab.png",
    cta: "Discover now",
    title: "زينة العرب",
    subtitle: "On everything today",
    isFeatured: true,
    isActive: true,

    products: [
      {
        _id: "41",
        name: "ميار",
        type: "variable",
        subtitle: "ميار",
        price: 180,
        description: "",
        sizes: ["s", "m", "l", "xl"],
        category: "ملابس",
        stock: 10,
        isFeatured: true,
        colors: [
          {
            name: "green",
            hex: "#797F69",
            images: [
              "https://69f78dbca0be0e562864a507.imgix.net/clother_mayar.png",
            ],
            variants: [
              {
                size: "s",
                sku: "TSH-BLC-S",
                stock: 2,
                isActive: true,
              },
            ],
          },
        ],

        isActive: true,
        createdAt: "2026-05-04T24:45:27.922+00:0",
      },
      {
        _id: "42",
        name: "لوجين",
        type: "variable",
        subtitle: "لوجين",
        price: 280,
        description: "",
        sizes: ["s", "m", "l", "xl"],
        category: "ملابس",
        stock: 10,
        isFeatured: true,
        colors: [
          {
            name: "marron",
            hex: "#A88C6E",
            images: [
              "https://69f78dbca0be0e562864a507.imgix.net/clothes_lojan.png",
            ],
            variants: [
              { size: "s", sku: "TSH-MAR-S", isActive: true, stock: 5 },
            ],
          },
          {
            name: "noir",
            hex: "#000000",
            images: [
              "https://69f78dbca0be0e562864a507.imgix.net/clothes_lojan.png",
            ],
            variants: [
              { size: "m", sku: "TSH-MAR-S", isActive: true, stock: 5 },
            ],
          },
        ],
        isActive: true,
        createdAt: "2026-05-03T24:45:27.922+00:0",
      },
      {
        _id: "43",
        name: "منيار",
        type: "variable",
        subtitle: "منيار",
        price: 280,
        description: "",
        sizes: ["s", "m", "l", "xl"],
        category: "ملابس",
        stock: 10,
        isFeatured: true,
        colors: [
          {
            name: "rose",
            hex: "A58A83",
            images: [
              "https://69f78dbca0be0e562864a507.imgix.net/clother_minyar.png",
            ],
            variants: [
              {
                sise: "m",
                stock: 4,
                sku: "tsh-rox",
                isActive: true,
              },
            ],
          },
        ],

        isActive: true,
        createdAt: "2026-05-02T24:45:27.922+00:0",
      },
      {
        _id: "44",
        name: "لارا",
        type: "variable",
        subtitle: "لارا",
        price: 380,
        description: "",
        sizes: ["s", "m", "l", "xl"],
        category: "ملابس",
        stock: 10,
        isFeatured: true,
        colors: [
          {
            name: "vert",
            hex: "#B8AA8E",
            images: [
              "https://69f78dbca0be0e562864a507.imgix.net/clothes_lara.png",
            ],
            variants: [
              {
                size: "xl",
                sku: "ths-veeret-xxl",
                stock: 3,
                isActive: true,
              },
            ],
          },
        ],

        isActive: true,
        createdAt: "2026-05-01T24:45:27.922+00:0",
      },
    ],
  },
];

export const DUMMY_CART_ITEM = [
  {
    _id: "1",
    quantity: 1,
    size: null,
    product: {
      _id: "1",
      name: "أنا الأبيض",
      subtitle: "أنا الأبيض",
      description: "",
      sizes: null,
      category: "عطور",
      price: 180,
      stock: 100,
      isFeatured: true,
      images: [
        "https://69f78dbca0be0e562864a507.imgix.net/parfum_ana_abiyedh_rouge.png",
      ],
      isActive: true,
      createdAt: "2026-05-02T21:45:27.922+00:0",
    },
  },
  {
    _id: "2",
    quantity: 1,
    size: null,
    product: {
      _id: "10",
      name: "بن نافع للعود",
      subtitle: "بن نافع للعود",
      price: 180,
      description: "",
      sizes: null,
      category: "باخور",
      stock: 10,
      isFeatured: true,
      images: [
        "https://69f78dbca0be0e562864a507.imgix.net/bakour_banafa_for_oud.png",
      ],
      isActive: true,
      createdAt: "2026-05-04T24:45:27.922+00:0",
    },
  },
  {
    _id: "3",
    quantity: 1,
    size: null,
    product: {
      _id: "2",
      name: "ressence type 11",
      subtitle: "ressence type 11",
      price: 80,
      description: "",
      sizes: null,
      category: "ساعات",
      stock: 10,
      isFeatured: true,
      images: [
        "https://69f78dbca0be0e562864a507.imgix.net/watch_ressence_type_11.png",
      ],
      isActive: true,
      createdAt: "2026-05-03T24:45:27.922+00:0",
    },
  },
];
export const DUMMY_RALATED_PRODUCTS_CART = [
  {
    _id: "1",
    name: "24 قراط ذهب",
    subtitle: "24 قراط ذهب",
    price: 250,
    description: "",
    sizes: null,
    category: "عطور",
    stock: 10,
    isFeatured: true,
    images: [
      "https://69f78dbca0be0e562864a507.imgix.net/parfum_24_carat_pure_gold.png",
    ],
    isActive: true,
    createdAt: "2026-05-01T21:45:27.922+00:0",
  },
  {
    _id: "2",
    name: "أسد",
    subtitle: "أسد",
    price: 250,
    description: "",
    sizes: null,
    category: "عطور",
    stock: 10,
    isFeatured: true,
    images: ["https://69f78dbca0be0e562864a507.imgix.net/parfum_assad.png"],
    isActive: true,
    createdAt: "2026-05-02T21:45:27.922+00:0",
  },
  {
    _id: "3",
    name: "بن نافع للعود",
    subtitle: "بن نافع للعود",
    price: 180,
    description: "",
    sizes: null,
    category: "باخور",
    stock: 10,
    isFeatured: true,
    images: [
      "https://69f78dbca0be0e562864a507.imgix.net/bakour_banafa_for_oud.png",
    ],
    isActive: true,
    createdAt: "2026-05-04T24:45:27.922+00:0",
  },
  {
    _id: "4",
    name: "بخور كويتي",
    subtitle: "بخور كويتي",
    price: 180,

    description: "",
    sizes: null,
    category: "باخور",
    stock: 10,
    isFeatured: true,
    images: ["https://69f78dbca0be0e562864a507.imgix.net/bakour_kwaiti.png"],
    isActive: true,
    createdAt: "2026-05-03T24:45:27.922+00:0",
  },
  {
    _id: "5",
    name: "عود فاخر",
    price: 250,

    description: "",
    sizes: null,
    category: "باخور",
    stock: 10,
    isFeatured: true,
    images: ["https://69f78dbca0be0e562864a507.imgix.net/bakour_oud_wood.png"],
    isActive: true,
    createdAt: "2026-05-02T24:45:27.922+00:0",
  },
  {
    _id: "6",
    name: "منيار",
    subtitle: "منيار",
    price: 280,
    description: "",
    sizes: ["s", "m", "l", "xl"],
    category: "ملابس",
    stock: 10,
    isFeatured: true,
    images: ["https://69f78dbca0be0e562864a507.imgix.net/clother_minyar.png"],
    isActive: true,
    createdAt: "2026-05-02T24:45:27.922+00:0",
  },
  {
    _id: "7",
    name: "لارا",
    subtitle: "لارا",
    price: 380,
    description: "",
    sizes: ["s", "m", "l", "xl"],
    category: "ملابس",
    stock: 10,
    isFeatured: true,
    images: ["https://69f78dbca0be0e562864a507.imgix.net/clothes_lara.png"],
    isActive: true,
    createdAt: "2026-05-01T24:45:27.922+00:0",
  },
];
export const PRODUCTS = [
  {
    _id: "11",
    name: "أنا الأبيض",

    type: "simple",
    subtitle: "نسخة محدودة • ١٠٠ مل",
    description: "",
    sizes: null,
    category: "عطور",
    subCategory: "women",
    brand: "لطافة",
    price: 180,
    stock: 100,
    isFeatured: true,
    images: [
      "https://69f78dbca0be0e562864a507.imgix.net/parfum_ana_abiyedh_rouge.png",
    ],
    isActive: true,
    createdAt: "2026-05-02T21:45:27.922+00:0",
  },
  {
    _id: "12",
    name: "عود الليل الملكي",
    type: "simple",
    subtitle: "نسخة محدودة • ١٠٠ مل",
    price: 250,
    description: "",
    sizes: null,
    category: "عطور",
    stock: 10,
    isFeatured: true,
    images: [
      "https://69f78dbca0be0e562864a507.imgix.net/parfum_oud_lail_maleki.png",
    ],
    isActive: true,
    createdAt: "2026-05-03T21:45:27.922+00:0",
  },
  {
    _id: "13",
    name: "أسد",
    type: "simple",
    subtitle: "نسخة محدودة • ١٠٠ مل",
    price: 250,
    description: "",
    sizes: null,
    category: "عطور",
    stock: 10,
    isFeatured: true,
    images: ["https://69f78dbca0be0e562864a507.imgix.net/parfum_assad.png"],
    isActive: true,
    createdAt: "2026-05-02T21:45:27.922+00:0",
  },
  {
    _id: "14",
    name: "24 قراط ذهب",
    type: "simple",
    subtitle: "نسخة محدودة • ١٠٠ مل",
    price: 250,
    description: "",
    sizes: null,
    category: "عطور",
    stock: 10,
    isFeatured: true,
    images: [
      "https://69f78dbca0be0e562864a507.imgix.net/parfum_24_carat_pure_gold.png",
    ],
    isActive: true,
    createdAt: "2026-05-01T21:45:27.922+00:0",
  },
  {
    _id: "21",
    name: "بن نافع للعود",
    type: "simple",
    subtitle: "بن نافع للعود",
    price: 180,
    description: "",
    sizes: null,
    category: "باخور",
    stock: 10,
    isFeatured: true,
    images: [
      "https://69f78dbca0be0e562864a507.imgix.net/bakour_banafa_for_oud.png",
    ],
    isActive: true,
    createdAt: "2026-05-04T24:45:27.922+00:0",
  },
  {
    _id: "22",
    name: "بخور كويتي",
    type: "simple",
    subtitle: "بخور كويتي",
    price: 180,

    description: "",
    sizes: null,
    category: "باخور",
    stock: 10,
    isFeatured: true,
    images: ["https://69f78dbca0be0e562864a507.imgix.net/bakour_kwaiti.png"],
    isActive: true,
    createdAt: "2026-05-03T24:45:27.922+00:0",
  },
  {
    _id: "23",
    name: "عود فاخر",
    type: "simple",
    price: 250,

    description: "",
    sizes: null,
    category: "باخور",
    stock: 10,
    isFeatured: true,
    images: ["https://69f78dbca0be0e562864a507.imgix.net/bakour_oud_wood.png"],
    isActive: true,
    createdAt: "2026-05-02T24:45:27.922+00:0",
  },
  {
    _id: "24",
    name: "بخور عشق العرب",
    type: "simple",
    subtitle: "بخور عشق العرب",
    price: 350,
    description: "",
    sizes: null,
    category: "باخور",
    stock: 10,
    isFeatured: true,
    images: [
      "https://69f78dbca0be0e562864a507.imgix.net/bakour_acheg_al_arab.png",
    ],
    isActive: true,
    createdAt: "2026-05-01T24:45:27.922+00:0",
  },
  {
    _id: "31",
    name: "luxury watch",
    type: "simple",
    subtitle: "luxury watch",
    price: 80,

    description: "",
    sizes: null,
    category: "ساعات",
    stock: 100,
    isFeatured: true,
    images: ["https://69f78dbca0be0e562864a507.imgix.net/watch_luxury.png"],
    isActive: true,
    createdAt: "2026-05-04T24:45:27.922+00:0",
  },
  {
    _id: "32",
    name: "ressence type 11",
    type: "simple",
    subtitle: "ressence type 11",
    price: 80,

    description: "",
    sizes: null,
    category: "ساعات",
    stock: 10,
    isFeatured: true,
    images: [
      "https://69f78dbca0be0e562864a507.imgix.net/watch_ressence_type_11.png",
    ],
    isActive: true,
    createdAt: "2026-05-03T24:45:27.922+00:0",
  },
  {
    _id: "33",
    name: "inspiration one",
    type: "simple",
    subtitle: "inspiration one",
    price: 80,

    description: "",
    sizes: null,
    category: "ساعات",
    stock: 10,
    isFeatured: true,
    images: [
      "https://69f78dbca0be0e562864a507.imgix.net/watch_inspiration.png",
    ],
    isActive: true,
    createdAt: "2026-05-02T24:45:27.922+00:0",
  },
  {
    _id: "34",
    name: "nautilus 5610p",
    type: "simple",
    subtitle: "nautilus 5610p",
    price: 80,

    description: "",
    sizes: null,
    category: "ساعات",
    stock: 10,
    isFeatured: true,
    images: [
      "https://69f78dbca0be0e562864a507.imgix.net/watch_patek_philip.png",
    ],
    isActive: true,
    createdAt: "2026-05-01T24:45:27.922+00:0",
  },
  {
    _id: "41",
    name: "ميار",
    type: "variable",
    subtitle: "ميار",
    price: 180,
    description: "",
    sizes: ["s", "m", "l", "xl"],
    category: "ملابس",
    stock: 10,
    isFeatured: true,
    colors: [
      {
        name: "green",
        hex: "#797F69",
        images: [
          "https://69f78dbca0be0e562864a507.imgix.net/clother_mayar.png",
          "https://69f78dbca0be0e562864a507.imgix.net/clothes_lojan.png",
        ],
        variants: [
          {
            size: "s",
            sku: "TSH-BLC-S",
            stock: 2,
            isActive: true,
          },
        ],
      },
    ],

    isActive: true,
    createdAt: "2026-05-04T24:45:27.922+00:0",
  },
  {
    _id: "42",
    name: "لوجين",
    type: "variable",
    subtitle: "لوجين",
    price: 280,
    description: "",
    sizes: ["s", "m", "l", "xl"],
    category: "ملابس",
    stock: 10,
    isFeatured: true,
    colors: [
      {
        name: "marron",
        hex: "#A88C6E",
        images: [
          "https://69f78dbca0be0e562864a507.imgix.net/clothes_lojan.png",
        ],
        variants: [{ size: "s", sku: "TSH-MAR-S", isActive: true, stock: 5 }],
      },
      {
        name: "noir",
        hex: "#000000",
        images: [
          "https://69f78dbca0be0e562864a507.imgix.net/clothes_lojan.png",
        ],
        variants: [{ size: "m", sku: "TSH-MAR-S", isActive: true, stock: 5 }],
      },
    ],
    isActive: true,
    createdAt: "2026-05-03T24:45:27.922+00:0",
  },
  {
    _id: "43",
    name: "منيار",
    type: "variable",
    subtitle: "منيار",
    price: 280,
    description: "",
    sizes: ["s", "m", "l", "xl"],
    category: "ملابس",
    stock: 10,
    isFeatured: true,
    colors: [
      {
        name: "rose",
        hex: "A58A83",
        images: [
          "https://69f78dbca0be0e562864a507.imgix.net/clother_minyar.png",
        ],
        variants: [
          {
            sise: "m",
            stock: 4,
            sku: "tsh-rox",
            isActive: true,
          },
        ],
      },
    ],

    isActive: true,
    createdAt: "2026-05-02T24:45:27.922+00:0",
  },
  {
    _id: "44",
    name: "لارا",
    type: "variable",
    subtitle: "لارا",
    price: 380,
    description: "",
    sizes: ["s", "m", "l", "xl"],
    category: "ملابس",
    stock: 10,
    isFeatured: true,
    colors: [
      {
        name: "vert",
        hex: "#B8AA8E",
        images: ["https://69f78dbca0be0e562864a507.imgix.net/clothes_lara.png"],
        variants: [
          {
            size: "xl",
            sku: "ths-veeret-xxl",
            stock: 3,
            isActive: true,
          },
        ],
      },
    ],

    isActive: true,
    createdAt: "2026-05-01T24:45:27.922+00:0",
  },
];
export const PROFILE_MENU = [
  { id: 1, title: "طلباتي", icon: "cube-sharp", route: "/orders" },
  {
    id: 2,
    title: "عناوين الشحن",
    icon: "location-outline",
    route: "/address",
  },
  { id: 4, title: "تقيماتي", icon: "star-outline", route: "/" },
  { id: 5, title: "طرق الدفع", icon: "cash-outline", route: "/" },

  { id: 6, title: "الإعدادات", icon: "settings-outline", route: "/settings" },
];
export const ADDRESSES = [
  {
    id: 1,
    type: "المنزل",
    phone: "+21640444336",
    state: "مدنين",
    city: "مدنين",
    codePostal: 4100,
    address: "شارع أبو بكر الصديق منزل عدد 2 طريق بني خداش",
    country: "تونس",
    isDefault: true,
  },
  {
    id: 2,
    type: "المكتب",
    phone: "+21620123456",
    state: "مدنين",
    city: "مدنين",
    codePostal: 4100,
    address: "شارع أبو بكر الصديق منزل عدد 2 طريق بني خداش",
    country: "تونس",
    isDefault: false,
  },
  {
    id: 3,
    type: "أخري",
    phone: "+21620123456",
    state: "مدنين",
    city: "مدنين",
    codePostal: 4100,
    address: "شارع أبو بكر الصديق منزل عدد 2 طريق بني خداش",
    country: "تونس",
    isDefault: false,
  },
];
